#!/bin/bash

cd "$HOME"
yadm submodule update --recursive --init

mkdir -p ~/bin

# os package install
if [ "$(uname)" == 'Darwin' ]; then
  echo 'bootstrap for macOS'

elif [ "$(uname)" == 'Linux' ]; then
  echo 'bootstrap for Linux'

  # debian base system
  if type apt > /dev/null 2>&1; then
    sudo apt update
    sudo apt install -y \
      git vim ctags zsh tmux xsel \
      ranger w3m-img atool caca-utils lynx highlight mediainfo poppler-utils
  fi

  # install fonts
  mkdir -p ~/.local/share/fonts
  cd ~/.local/share/fonts
  if [ ! -e "Cica-Regular.ttf"]; then
    curl -s https://api.github.com/repos/miiton/Cica/releases/latest \
      | grep browser_download_url \
      | grep _with_emoji.zip \
      | head -n 1 \
      | cut -d '"' -f 4 \
      | wget -qi -
    unzip Cica_*_with_emoji.zip "*.ttf"
    rm -f Cica_*_with_emoji.zip
  fi
  cd ~
fi

# install starship
if ! command -v starship &> /dev/null; then
  curl -fsSL https://starship.rs/install.sh | bash
fi

if [ ! -e ~/.zinit/bin ]; then
  echo 'initializing zinit'
  mkdir -p ~/.zinit
  git clone https://github.com/zdharma/zinit.git ~/.zinit/bin
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

zsh

