#!/bin/bash

cd "$HOME"
yadm submodule update --recursive --init

# os package install
if [ "$(uname)" == 'Darwin' ]; then
  echo 'bootstrap for macOS'
elif [ "$(uname)" == 'Linux' ]; then
  echo 'bootstrap for Linux'

  # debian base system
  if type apt > /dev/null 2>&1; then
	sudo apt update
    sudo apt install -y \
	  build-essential cmake git python3-dev \
	  vim-nox ctags zsh tmux xsel zathura \
	  mono-complete golang nodejs default-jdk npm \
	  ranger w3m-img atool caca-utils elinks lynx highlight python-pygments mediainfo exiftool poppler-utils mupdf-tools
  fi

fi


if [ ! -e ~/.zinit/bin ]; then
  echo 'initializing zinit'
  mkdir -p ~/.zinit
  git clone https://github.com/zdharma/zinit.git ~/.zinit/bin
fi

